2025-03-01 16:57:25,115 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:43]
2025-03-01 16:57:25,135 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:665]
2025-03-01 16:58:54,437 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:43]
2025-03-01 16:58:54,455 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:665]
2025-03-01 17:00:42,867 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:43]
2025-03-01 17:00:42,885 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:742]
2025-03-01 17:01:02,706 ERROR: 数据收集出错: 'NoneType' object is not subscriptable [in C:\Users\28637\Desktop\demo1\实例3\app.py:545]
2025-03-01 17:01:57,455 ERROR: 数据收集出错: 'NoneType' object is not subscriptable [in C:\Users\28637\Desktop\demo1\实例3\app.py:545]
2025-03-01 17:02:52,251 ERROR: 数据收集出错: 'NoneType' object is not subscriptable [in C:\Users\28637\Desktop\demo1\实例3\app.py:545]
2025-03-01 17:03:17,166 ERROR: 数据收集出错: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO alert (device_id, timestamp, alert_type, message, severity, resolved, resolved_time, resolved_by, resolution_notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id]
[parameters: (2, 1740819692.44797, 'high_latency', '设备 边界路由器 (192.168.1.2) 延迟过高: 199.1ms > 100ms', 'warning', 0, None, None, None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8) [in C:\Users\28637\Desktop\demo1\实例3\app.py:787]
2025-03-01 17:03:47,169 ERROR: 数据收集出错: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO alert (device_id, timestamp, alert_type, message, severity, resolved, resolved_time, resolved_by, resolution_notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id]
[parameters: (2, 1740819692.44797, 'high_latency', '设备 边界路由器 (192.168.1.2) 延迟过高: 199.1ms > 100ms', 'warning', 0, None, None, None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8) (Background on this error at: https://sqlalche.me/e/20/7s2a) [in C:\Users\28637\Desktop\demo1\实例3\app.py:787]
2025-03-01 17:04:17,172 ERROR: 数据收集出错: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO alert (device_id, timestamp, alert_type, message, severity, resolved, resolved_time, resolved_by, resolution_notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id]
[parameters: (2, 1740819692.44797, 'high_latency', '设备 边界路由器 (192.168.1.2) 延迟过高: 199.1ms > 100ms', 'warning', 0, None, None, None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8) (Background on this error at: https://sqlalche.me/e/20/7s2a) [in C:\Users\28637\Desktop\demo1\实例3\app.py:787]
2025-03-01 17:04:18,743 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:43]
2025-03-01 17:04:18,760 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:742]
2025-03-01 17:07:10,811 ERROR: 数据收集出错: 'NoneType' object is not subscriptable [in C:\Users\28637\Desktop\demo1\实例3\app.py:545]
2025-03-01 17:07:21,817 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:44]
2025-03-01 17:07:21,836 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:743]
2025-03-01 17:07:31,864 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:44]
2025-03-01 17:07:31,881 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:744]
2025-03-01 17:07:44,926 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:44]
2025-03-01 17:07:44,946 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:770]
2025-03-01 17:09:37,429 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:44]
2025-03-01 17:09:37,447 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:770]
2025-03-01 17:10:09,594 ERROR: 数据收集出错: 'NoneType' object is not subscriptable [in C:\Users\28637\Desktop\demo1\实例3\app.py:545]
2025-03-01 17:11:04,389 ERROR: 数据收集出错: 'NoneType' object is not subscriptable [in C:\Users\28637\Desktop\demo1\实例3\app.py:545]
2025-03-01 17:12:11,867 ERROR: 数据收集出错: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO alert (device_id, timestamp, alert_type, message, severity, resolved, resolved_time, resolved_by, resolution_notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id]
[parameters: (1, 1740820202.305762, 'high_latency', '设备 核心交换机 (192.168.1.1) 延迟过高: 104.4ms > 100ms', 'warning', 0, None, None, None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8) [in C:\Users\28637\Desktop\demo1\实例3\app.py:815]
2025-03-01 17:12:41,870 ERROR: 数据收集出错: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO alert (device_id, timestamp, alert_type, message, severity, resolved, resolved_time, resolved_by, resolution_notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id]
[parameters: (1, 1740820202.305762, 'high_latency', '设备 核心交换机 (192.168.1.1) 延迟过高: 104.4ms > 100ms', 'warning', 0, None, None, None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8) (Background on this error at: https://sqlalche.me/e/20/7s2a) [in C:\Users\28637\Desktop\demo1\实例3\app.py:815]
2025-03-01 17:12:47,270 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:44]
2025-03-01 17:12:47,290 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:770]
2025-03-01 17:12:47,794 ERROR: 数据收集出错: 'NoneType' object is not subscriptable [in C:\Users\28637\Desktop\demo1\实例3\app.py:545]
2025-03-01 17:13:02,367 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:44]
2025-03-01 17:13:02,387 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:769]
2025-03-01 17:13:14,400 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:44]
2025-03-01 17:13:14,419 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:786]
2025-03-01 17:13:25,428 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:44]
2025-03-01 17:13:25,447 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:786]
2025-03-01 17:13:58,573 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:44]
2025-03-01 17:13:58,593 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:788]
2025-03-01 17:14:20,693 INFO: 网络监控平台启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:44]
2025-03-01 17:14:20,713 INFO: 数据收集后台任务启动 [in C:\Users\28637\Desktop\demo1\实例3\app.py:788]
